/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.types.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv` (hash: ec2907c727619e88fa596aaef45da88f)
interface __BaseEnv_CloudflareEnv {
	SUPABASE_URL: string;
	CORS_ORIGINS: string;
	OPENAI_MODEL: string;
	OPENAI_IMAGE_MODEL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "CORS_ORIGINS" | "OPENAI_MODEL" | "OPENAI_IMAGE_MODEL">> {}
}
